### ISSUE TITLE
German localisation

### ISSUE THREAD

**Issue by ThxAndBye** [MaverickTse/waifu2x_caffe_multilang_gui#5]
Hey,

i had some time to waste so i created a german localisation for your GUI.
Gid didn't want me to upload as a zip, so i have a txt file for you.

Greetings

[UILang.de-DE.txt](https://github.com/MaverickTse/waifu2x_caffe_multilang_gui/files/72541/UILang.de-DE.txt)

**Comment by MaverickTse** [comment]
Thank you very much!　Now bundled in Release 1.4.4
